import './globals.css'
export const metadata = {
  title: '3D Shop-Card',
  description: 'Generated by Deaa Aldin Alawad',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="de">
      <body className='bg-black'>{children}</body>
    </html>
  )
}
